### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by shengcheng** [yilundu/podnet#1]
Hello, 

I really appreciate this work. From the code, I find that some code missing in this repository:\
`from .inverse_graphics import Mask2Cube, Cube2Mask, Mask2CubeManual, Cube2MaskManual`
Can you check this part? Thanks!

**Comment by yilundu** [comment]
Hi I think I have added it -- let me know if you have any issues!

**Comment by shengcheng** [comment]
Sorry for confusing. I mean the `inverse_graphics` file is missing.

**Comment by yilundu** [comment]
I believe its added at https://github.com/yilundu/podnet/blob/master/models/inverse_graphics.py -- do you see it?

**Comment by shengcheng** [comment]
I can find it right now. Thank you!
